"""Добавил поля админа и активного юзера для админ-панели

Revision ID: 3c7b20e1fd73
Revises: aeb41a10779e
Create Date: 2025-12-07 17:19:40.067739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c7b20e1fd73'
down_revision: Union[str, Sequence[str], None] = 'aeb41a10779e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'session_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.execute('UPDATE users SET is_active = TRUE')
    op.execute('UPDATE users SET is_admin = TRUE')
    op.alter_column('users', 'is_active', nullable=False)
    op.alter_column('users', 'is_admin', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'is_active')
    op.alter_column('sessions', 'session_id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###
